SSID = 'ssid'
PASSWORD = 'password'
OWM_CITY_ID = 'owm_city_id'
OWM_API_KEY = 'own_api_key'
OWM_URL = 'owm_url'
THINKSPEAK_API_KEY = 'thinkspeak_api_key'
THINKSPEAK_BASE_URL = 'thinkspeak_base_url'
THINKSPEAK_FIELDS_URL = 'thinkspeak_fields_url'
